name: Unit tests for all microservices

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  run_tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Run gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests for inventory service
        run: ./gradlew :inventory-service:test
        continue-on-error: true

      - name: Run unit tests for order service
        run: ./gradlew :order-service:test
        continue-on-error: true

      - name: Upload HTML reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: html-test-report
          path: '**/build/reports/tests/test'

      - name: Show test results
        if: always()
        run: |
          echo "Inventory tests:"
          cat inventory-service/build/test-results/test/TEST-*.xml || true
          
          echo "Order tests:"
          cat order-service/build/test-results/test/TEST-*.xml || true
